### ISSUE TITLE
Meta: Teams fixes for OpenSHMEM 1.5

### ISSUE THREAD

**Issue by nspark** [gmegan/specification#157]
The following areas were identified as needing some cleanup after ratifying the Teams proposal for OpenSHMEM 1.5:

- [ ] Error handling; see #158 
- [ ] Rank ordering within team
- [ ] Configuration structure
- [ ] Inter-team atomicity
